audiozone_sys/urls.py
from django.urls import path
from .views import audio_view, music_view

app_name = 'audiozone_sys'  # Додайте цю строку для реєстрації простору імен

urlpatterns = [
    path('audio/', audio_view, name='audio'),
    path('music/', music_view, name='music'),
]

auth_sys/urls.py
from django.urls import path
from . import views

app_name = 'auth_sys'

urlpatterns = [
    # Тут будуть додані URL-шаблони для messanjer_sys
    path('login', views.logination_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('register', views.register_view, name="register"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static

def index(request):
    return render(request, 'index.html')

def index_o_info(request):
    return render(request, 'index_o_info.html')

urlpatterns = [
    path('', index, name='index'),
    path('cos', index_o_info, name='index_o_info'),
    path('admin/', admin.site.urls),
    path('auth/', include('auth_sys.urls')),
    path('messenger/', include('messenger_sys.urls')),
    path('video/', include('videozone_sys.urls')),
    path('search/', include('searchzone_sys.urls')),
    path('projectzone/', include('projectzone_sys.urls')),
    path('profile/', include('profile_sys.urls')),
    path('photo/', include('photozone_sys.urls')),
    path('audio/', include('audiozone_sys.urls')),
    path('cos/', include('courceszone_sys.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photozone_sys/urls.py
from django.urls import path
from . import views

app_name = 'photozone_sys'

urlpatterns = [
   path('photos/', views.photoszone_view, name='photos'),
   path('images/', views.imgs_4_designs_view, name='images')
] 

profile_sys/urls.py
from django.urls import path
from .views import user_profile_view

app_name = 'profilezone_sys'

urlpatterns = [
    path('profile/', user_profile_view, name='profile'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" >
<head>
  {% load static %}
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'><link rel="stylesheet" href="./style.css">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Matrix Auth{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link rel="icon" type="image/jpg" href="{% static 'logo/favicon.jpg' %}">  
</head>
<body>
<!-- partial:index.partial.html -->
<header>
  <div class="wrapper">
    <div class="logo"><a href="{% url 'index' %}">VanillaSM</a></div>
    <input type="radio" name="slider" id="menu-btn" class="header">
    <input type="radio" name="slider" id="close-btn" class="header">
    <ul class="header-links">
      <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>


      <li>
        <a href="#" class="desktop-item">Zones1</a>
        <input type="checkbox" id="showDrop" class="header">
        <label for="showDrop" class="mobile-item">Dropdown Menu</label>
        <ul class="drop-menu">
          <li><a href="#">Projects</a></li>
          <li><a href="#">Drop menu 2</a></li>
        </ul>
      </li>


      <li>
        <a href="#" class="desktop-item">Zones2</a>
        <input type="checkbox" id="showMega" class="header">
        <label for="showMega" class="mobile-item">Zones2</label>

        <div class="mega-box">
          <div class="content">
            <div class="row">
              <img src="https://fadzrinmadu.github.io/hosted-assets/responsive-mega-menu-and-dropdown-menu-using-only-html-and-css/img.jpg" alt="">
            </div>

            <div class="row">
              <header>Audio</header>
              <ul class="mega-links">
                <hr>
                <li><a href="#"">Audio</a></li>
                <li><a href="{% url 'audiozone_sys:audio' %}">Audio</a></li>
                <li><a href="{% url 'audiozone_sys:music' %}">Music</a></li>
              </ul>
            </div>

            <div class="row">
              <header>Video</header>
              <ul class="mega-links">
                <hr>
                <li><a href="#"">Video</a></li>
                <li><a href="{% url 'videozone_sys:short-video' %}">Short</a></li>
                <li><a href="{% url 'videozone_sys:long-video' %}">Long</a></li>
              </ul>
            </div>

            <div class="row">
              <header>Photo</header>
              <ul class="mega-links">
                <hr>
                <li><a href="#"">Photo</a></li>
                <li><a href="{% url 'photozone_sys:photos' %}"">Posts</a></li>
                <li><a href="{% url 'photozone_sys:images' %}">Designs</a></li>
              </ul>
            </div>
          </div>
        </div>
      </li>


      <li>
        {% if user.is_authenticated %}
        <label for="showDrop" class="mobile-item">Dropdown Menu</label>
        <ul class="drop-menu">
          <li><a href="{% url 'auth_sys:login' %}">Add acoount</a></li>
          <li><a href="{% url 'auth_sys:register' %}">Regist new account</a></li>
          <li><a href="{% url 'auth_sys:logout' %}">Exit from current</a></li>
        </ul>
          <a href="{% url 'profilezone_sys:profile' %}" class="desktop-item">Accounts</a>
          <input type="checkbox" id="showAccounts" class="header">
          <label for="showAccounts" class="mobile-item">Accounts</label>
          <ul class="drop-menu">
            {% for account in user.smuser_set.all %}
            <li><a href="{% url 'switch_account' account.id %}">{{ account.display_name }}</a></li>
            {% endfor %}
          </ul>
        {% else %}
          <a href="#" class="desktop-item">Accounts</a>
        {% endif %}
      </li>
      <li><a href="{% url 'index_o_info' %}">VanillaCoS</a></li>
    </ul>
    <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
  </div>
</header>

<div class="body-text">
  {% block content %}
  {% endblock %}
</div>
</body>
</html>

<script>
const header = document.querySelector('header');
const headerHeight = header.offsetHeight;

// Встановлюємо значення CSS-перемінної
document.documentElement.style.setProperty('--header-height', `${headerHeight}px`);

// Додаємо обробник події для оновлення при зміні розміру вікна
window.addEventListener('resize', () => {
    const newHeaderHeight = header.offsetHeight;
    document.documentElement.style.setProperty('--header-height', `${newHeaderHeight}px`);
});
</script>

templates/base_o_info.html
<!DOCTYPE html>
<html lang="en" >
<head>
{% load static %}
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'><link rel="stylesheet" href="./style.css">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{% block title %}Matrix Auth{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="icon" type="image/jpg" href="{% static 'logo/favicon.jpg' %}">  
</head>
<body>

<header>
<div class="wrapper">
    <div class="logo"><a href="{% url 'index_o_info' %}">VanillaCoS</a></div>
    <input type="radio" name="slider" id="menu-btn" class="header">
    <input type="radio" name="slider" id="close-btn" class="header">
    <ul class="header-links">
    <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
    <li>
    <a href="#" class="desktop-item">Cources</a>
    <input type="checkbox" id="showMega" class="header">
    <label for="showMega" class="mobile-item">Cources</label>
    <div class="mega-box">
        <div class="content">
            <div class="row">
            <img src="https://fadzrinmadu.github.io/hosted-assets/responsive-mega-menu-and-dropdown-menu-using-only-html-and-css/img.jpg" alt="">
            </div>
            <div class="row">
            <header>Graphick editing</header>
            <ul class="mega-links">
                <li><a href="#"">Graphick editing</a></li>
                <li><a href="{% url 'courceszone_sys:photos-cos' %}">Photo editing</a></li>
                <li><a href="{% url 'courceszone_sys:videos-cos' %}">Video editing</a></li>
                <li><a href="{% url 'courceszone_sys:audios-cos' %}">Audio editing</a></li>
                <li><a href="{% url 'courceszone_sys:3d-models-cos' %}">3D editing</a></li>
            </ul>
            </div>
            <div class="row">
                <header>All else</header>
                <ul class="mega-links">
                    <li><a href="#"">All else</a></li>
                    <li><a href="{% url 'courceszone_sys:codes-cos' %}"">Code</a></li>
                    <li><a href="{% url 'courceszone_sys:finance-cos' %}">Finance</a></li>
                    <li><a href="{% url 'courceszone_sys:cryptography-cos' %}">Cryptography</a></li>
                    <li><a href="{% url 'courceszone_sys:science-cos' %}">Scince</a></li>
                </ul>
            </div>
        </div>
    </div>
    </li>
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'profilezone_sys:profile' %}" class="desktop-item">Accounts</a>
        <input type="checkbox" id="showAccounts" class="header">
        <label for="showAccounts" class="mobile-item">Accounts</label>
        <ul class="drop-menu">
            {% for account in user.smuser_set.all %}
            <li><a href="{% url 'switch_account' account.id %}">{{ account.display_name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <a href="#" class="desktop-item">None</a>
        {% endif %}
    </li>
    <li><a href="{% url 'index' %}">VanillaSM</a></li>
    </ul>
    <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
</div>
<div class="arrow-down" id="toggleArrow">&#x25BC;</div>
<div class="new_group" id="newGroup" style="display: none;">
    <h1>Створити Курс</h1>
    <form method="post" action="{% url 'courceszone_sys:ncource' %}">
        {% csrf_token %}
        <p>
            <label for="id_c_title">Title:</label>
            <input type="text" name="c_title" maxlength="255" required id="id_c_title" class="input">
        </p>
        <p>
            <label for="id_c_description">Description:</label>
            <textarea name="c_description" id="id_c_description" required></textarea>
        </p>
        <p>
            <label for="id_c_type">C Type:</label>
            <select name="c_type" id="id_c_type">
                <option value="code">Code</option>
                <option value="audio">Audio</option>
                <option value="video">Video</option>
                <option value="photos">Photos</option>
                <option value="3d-models">3D Models</option>
                <option value="finance">Finance</option>
                <option value="cryptography">Cryptography</option>
                <option value="science">Science</option>
            </select>
        </p>
        <p>
            <label for="id_c_prize">Prize:</label>
            <input type="number" name="c_prize" id="id_c_prize" required>
        </p>
        <p>
            <label for="id_c_files">Files:</label>
            <input type="text" name="c_files" maxlength="300" id="id_c_files">
        </p>
        <p>
            <label for="id_c_pay_choices">Pay Choices:</label>
            <select name="c_pay_choices" id="id_c_pay_choices">
                <option value="card_number">Card number</option>
                <option value="iban">IBAN</option>
            </select>
        </p>
        <button type="submit">Зберегти</button>
    </form>
</div>
</header>




<div class="body-text">
{% block content %}
{% endblock %}
</div>


<!-- <footer>
<div class="wrapper">
    <ul>
    <li><a class="desktoa-item=">Привіт! Дякую, за використання нашого веб додатку.</a></li>
    <li><a class="desktoa-item">Ми з України і раді бачити тебе в нас. Якщо ми тобі цікаві, ти можеш знайти нас</a></li>
    <li><a class="desktoa-item">Matrix:</a></li>
    <li><a class="desktoa-item">TikTok:</a></li>
    <li><a class="desktoa-item">YouTube:</a></li>
    <li><a class="desktoa-item">Drykarnya:</a></li>
    <li><a class="desktoa-item">GitHub:</a></li>
    </ul>
</div>
</footer> -->
</body>
</html>


<script>
    document.getElementById('toggleArrow').addEventListener('click', function() {
        var newGroup = document.getElementById('newGroup');
        if (newGroup.style.display === 'none' || newGroup.style.display === '') {
            newGroup.style.display = 'block';
        } else {
            newGroup.style.display = 'none';
        }
    });

    const header = document.querySelector('header');
const headerHeight = header.offsetHeight;

// Встановлюємо значення CSS-перемінної
document.documentElement.style.setProperty('--header-height', `${headerHeight}px`);

// Додаємо обробник події для оновлення при зміні розміру вікна
window.addEventListener('resize', () => {
    const newHeaderHeight = header.offsetHeight;
    document.documentElement.style.setProperty('--header-height', `${newHeaderHeight}px`);
});

</script>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Ласкаво просимо!</h1>
    {% if user.is_authenticated %}
        <p>Ви увійшли як {{ user.authentificator }}</p>
        <a href="{% url 'auth_sys:logout' %}">Вийти</a>
    {% else %}
        <p>Будь ласка, <a href="{% url 'auth_sys:login' %}">увійдіть</a> або 
        <a href="{% url 'auth_sys:register' %}">зареєструйтесь</a></p>
    {% endif %}
</div>
{% endblock %} 

templates/index_o_info.html
{% extends 'base_o_info.html' %}

{% block content %}

<h1>Hello welcome to the source of cources</h1>

{% endblock %} 